name: skillup-backend
services:
  - name: api
    type: web
    instance_type: free
    regions:
      - sin
    git:
      repository: github.com/As-arya/Skill_Up
      branch: main
    build:
      buildpack:
        build_command: "cd skillup-backend && npm install && npm run build && npx prisma generate"
        run_command: "cd skillup-backend && npx prisma migrate deploy && npm start"
    ports:
      - port: 3000
        protocol: http
    env:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
